### ISSUE TITLE
Information encoded into the token

### ISSUE THREAD

**Issue by phev8** [Influenzanet/authentication-service#2]
Idea for the token's content was to encode the user id and only the current role. So each request has only a single role assigned. For any incoming request, the auth-service decodes the token, the decoded information, such as the ``user_id`` and ``role`` can be attached to the downstream requests (by the api gateway probably). So other services can filter, if they allow the given request to be executed with the given role. 

The clients can store different tokens at the same time, and they should send the correct token (e.g. one for participant requests, other one for admin requests etc.). More typically, different applications will use mainly different request types almost exclusively. E.g., researcher web fronted uses mostly the researcher tokens but participant app uses only participant tokens. 

So generally, we should try to make tokens as short as possible, because they are attached to (almost) every request sent out and internally propagated. 

@despia Do you agree, or you think it's better to send always the full list of roles, a given user has, with the token? Then how would you decide if the user entered it's password again to be admin? Also theoretically, we can use different expiration intervals for different token times (e.g. admin token can expire much faster).

**Comment by despia** [comment]
As discussed we will only include the one `role` that was authenticate via the request inside the token, accompanied by the `user_id`.
