### ISSUE TITLE
Authorise for specific roles

### ISSUE THREAD

**Issue by phev8** [Influenzanet/authentication-service#3]
I was looking at the ``login-admin`` and ``login-researcher`` endpoints, and I think it would be a better abstraction, to implement the decision, if somebody can be admin or researcher in the ``user-management-service``.

I imagine it like so:
1) api gateway receivers request for admin login and forwards it to authentication service
2) authentication service checks if username and password are there and correct format, when everything alright, sends request to user management
3) user management checks if user exists, when found, checks if passwords hashes are correct, when ok, checks if user has the requested role. When all went ok, ``user_id`` is sent back.
4) if receives ``user_id``, meaning user has permission for the role, it generates the appropriate token, and sends back
5) api gateway relays the token the to client app

The advantage I see here, is that item 3 abstract the whole logic of role lookup, leaving other services independent of the implementation, if this is an array of strings, or separate databases for looking that up. 

@despia What do you think, would that work? I know it's somehow more code, partly duplicated in different services. But, I think, it improves maintainability and flexibility.

**Comment by despia** [comment]
This has been implemened in 8007b4c.
