### ISSUE TITLE
HasRole method is used only in tests

### ISSUE THREAD

**Issue by phev8** [Influenzanet/authentication-service#5]
Is the``HasRole()`` method used anywhere else than in the test to mock the role authentication, or is it intended to be used for something else than this? 

If the answer is no, we should consider to move it into the test file, keeping other files as lean as possible. @despia What do you think?

**Comment by despia** [comment]
You are correct. `HasRole()` will be used in the user-management to check for the existence of the requested role, but not in the authentication-service.

**Comment by despia** [comment]
Changed in f0e3263a6662e21221f11abecda103eed5dfaaa2

**Comment by despia** [comment]
@phev8 After changing the way login works this should also apply to the `UserModel`?

**Comment by phev8** [comment]
Yes, I think so as well.

**Comment by despia** [comment]
Changed in 1530c6b6c5db4cebb6dc35de94de82d6d0f1f5a0
