### ISSUE TITLE
dep files out of date

### ISSUE THREAD

**Issue by milovanderlinden** [Influenzanet/authentication-service#9]
Branch: dev
Go version: 1.14

If I remove `Gopkg.toml` and `Gopkg.lock` and run `dep init`, my new files are different, but they work. Once I have ran `dep init` I can succesfully run `go test --short`. I will create a pull request.

**Comment by milovanderlinden** [comment]
Pull request committed.

**Comment by milovanderlinden** [comment]
![dependencies](https://user-images.githubusercontent.com/106038/77707155-98706f80-6fc4-11ea-8475-b4a08f6ac177.png)

**Comment by phev8** [comment]
@milovanderlinden what is your experience with go modules?
when we started with dep - they were not really around yet - but if we don't need additional dependency of dep and can handle the same with the built in go tools...

**Comment by phev8** [comment]
I tried go modules - seems to work well out of the box, so I will remove dep - and update the docker file.
